# shellcheck shell=bash
# Guard test rows for bundle k8s. Sourced by bundles/core/guard/tests/run.sh after lib.sh
# (helpers: t EXPECTED 'cmd' | tc EXPECTED CWD 'cmd' | tr 'reason-re' 'cmd' | g EXPECTED 'cmd' in a real dir).

# ---- Kubernetes: reads pass -------------------------------------------------------
t pass  'kubectl get pods -A'
t pass  'kubectl --context dev-cluster --request-timeout=20s get nodes -o json | jq ".items|length"'
t pass  'kubectl -n shop logs deploy/shop-api --tail=50'
t pass  'kubectl rollout status deploy/shop-api -n shop --context dev-cluster'
t pass  'kubectl rollout history deploy/shop-api -n shop'
t pass  'kubectl config get-contexts'
t pass  'kubectl config current-context'
t pass  'kubectl config view --minify -o jsonpath="{.contexts[*].name}"'
t pass  'kubectl auth can-i create deployments -n shop --context dev-cluster'
t pass  'kubectl get --raw /api/v1/namespaces/cattle-monitoring-system/services/rancher-monitoring-prometheus:9090/proxy/api/v1/query?query=up'
t pass  'kubectl get secrets -n shop'
t pass  'kubectl describe secret shop-db -n shop'
t pass  'kubectl get secret shop-db -n shop -o wide'
t pass  'kubectl apply -f manifest.yaml --dry-run=server'
t pass  'kubectl diff -f manifest.yaml'
t pass  'k8s health --context dev-cluster'
t pass  'ls -la ~/.kube/'
t pass  'KUBECONFIG=~/.kube/config kubectl --context dev2-cluster get ns'
t pass  'helm list -n shop -o json'
t pass  'helm history shop -n shop'
t pass  'helm status shop -n shop'
t pass  'helm template ./chart -f values.yaml'
t pass  'helm upgrade --install shop ./chart -n shop --dry-run=server'
t pass  'argocd app get shop'
t pass  'pulumi preview'
# ---- Kubernetes: mutations ask, however wrapped or flagged ------------------------
t ask   'kubectl delete ns test'
t ask   'bash -c "kubectl delete ns test"'
t ask   'cd ~/dev/gitops && kubectl apply -k overlays/dev'
t ask   'kubectl -n shop delete pod shop-api-0'
t ask   'kubectl --context dev-cluster -n shop scale deploy/shop-api --replicas=0'
t ask   'kubectl get pods -n shop -o name | xargs kubectl -n shop delete'
t ask   'kubectl apply -f manifest.yaml --dry-run=none'
t ask   'kubectl label ns shop team=team'
t ask   'kubectl annotate deploy/shop-api -n shop note=x'
t ask   'kubectl set image deploy/shop-api api=repo/img:1.2.3 -n shop'
t ask   'kubectl run debugbox --image=busybox -n shop'
t ask   'kubectl expose deploy/shop-api --port=80 -n shop'
t ask   'kubectl autoscale deploy/shop-api --min=1 --max=3 -n shop'
t ask   'kubectl certificate approve csr-abc'
t ask   'kubectl auth reconcile -f rbac.yaml'
t ask   'kubectl rollout restart deploy/shop-api -n shop'
t ask   'kubectl rollout undo deploy/shop-api -n shop'
t ask   'kubectl edit deploy/shop-api -n shop'
t ask   'kubectl patch deploy/shop-api -n shop -p "{}"'
t ask   'kubectl replace -f manifest.yaml'
t ask   'kubectl drain node-1 --ignore-daemonsets'
t ask   'kubectl cordon node-1'
t ask   'kubectl uncordon node-1'
t ask   'kubectl taint nodes node-1 gpu=true:NoSchedule'
t ask   'kubectl create token shop-sa -n shop'
t ask   'kubectl exec -it shop-api-0 -n shop -- sh'
t ask   'kubectl -n shop exec shop-api-0 -- env'
t ask   'kubectl attach shop-api-0 -n shop'
t ask   'kubectl cp shop/shop-api-0:/tmp/x /tmp/x'
t ask   'kubectl debug node/node-1 -it --image=busybox'
t ask   'kubectl port-forward svc/shop 8080:80 -n shop'
t ask   'kubectl proxy --port=8001'
# ---- Secret data output: deny unless piped through the redactor -------------------
t deny  'kubectl get secret shop-db -n shop -o yaml'
t deny  'kubectl -n shop get secrets -o json'
t deny  'kubectl get secret shop-db -n shop -ojson | jq .data'
t deny  'kubectl get secret shop-db -n shop -o jsonpath="{.data.password}" | base64 -d'
t deny  'kubectl get secret shop-db -n shop -o go-template="{{.data}}"'
t deny  'kubectl get secrets,configmaps -n shop -o yaml'
t deny  'kubectl get --raw /api/v1/namespaces/shop/secrets/shop-db'
t deny  'bash -c "kubectl get secret shop-db -n shop -o yaml"'
t pass  'kubectl get secret shop-db -n shop -o json | k8s redact'
t pass  'kubectl get secrets -n shop -o json | k8s secret-keys -'
# ---- helm: values/all/manifest ask unless every clause is redacted ----------------
t ask   'helm get values shop -n shop'
t ask   'helm get all shop -n shop'
t ask   'helm get manifest shop -n shop'
t ask   'helm get values shop -n shop | yq .db'
t ask   'helm get values a -n shop | k8s redact; helm get values b -n shop'
t allow 'helm get values shop -n shop --kube-context dev-cluster | k8s redact'
t allow 'helm get manifest shop -n shop --kube-context dev-cluster | k8s redact'
t ask   'helm install shop ./chart -n shop'
t ask   'helm upgrade shop ./chart -n shop'
t ask   'helm uninstall shop -n shop'
t ask   'helm rollback shop 3 -n shop'
t ask   'helm test shop -n shop'
t ask   'helm push chart.tgz oci://registry/charts'
# ---- kubeconfig: reads and edits deny ---------------------------------------------
t deny  'kubectl config use-context prod-cluster'
t deny  'kubectl config set-context --current --namespace=shop'
t deny  'kubectl config set-credentials admin --token=abc'
t deny  'kubectl config set clusters.x.server https://203.0.113.4'
t deny  'kubectl config unset users.admin'
t deny  'kubectl config delete-context dev2-cluster'
t deny  'kubectl config delete-cluster dev2-cluster'
t deny  'kubectl config delete-user admin'
t deny  'kubectl config rename-context old new'
t deny  'bash -c "kubectl config use-context prod-cluster && kubectl get ns"'
t deny  'kubectl config view --raw'
t deny  'kubectl config view --minify --flatten --raw -o json'
t deny  'kubectl --context dev-cluster config view --raw=true'
t deny  'cat ~/.kube/config'
t deny  'cat $KUBECONFIG'
t deny  'cat "${KUBECONFIG}"'
t deny  'yq .users /home/u/.kube/prod-cluster-config.yaml'
t deny  'head -5 $HOME/.kube/config.backup'
t deny  'python3 -c "print(open(\"/home/u/.kube/config\").read())"'
t deny  'cd /tmp && cat ~/.kube/eks-config.yaml'
t deny  'grep token ~/.kube/config'
t deny  'cp ~/.kube/config /tmp/kc'
t deny  'aws eks update-kubeconfig --name eks-prod --region ap-southeast-1'
t deny  'eksctl utils write-kubeconfig --cluster eks-prod'
# ---- other infra tools ------------------------------------------------------------
t ask   'flux reconcile kustomization apps --with-source'
t ask   'eksctl scale nodegroup --cluster eks-prod --name ng-1 --nodes 3'
t ask   'argocd app sync shop'
t ask   'pulumi up'
t ask   'terraform apply'
# ---- reason strings carry context / namespace / [PROD] ----------------------------
tr 'context=dev-cluster ns=shop\)'          'kubectl delete pod x -n shop'
tr 'context=prod-cluster ns=shop \[PROD\]'      'kubectl --context prod-cluster delete pod x -n shop'
tr 'context=prod-cluster ns=shop \[PROD\]'      'kubectl --context=prod-cluster -n shop scale deploy/x --replicas=0'
tr 'eks-prod \[PROD\]'                  'kubectl --context arn:aws:eks:ap-southeast-1:111122223333:cluster/eks-prod delete pod x'   # gate-allow: example EKS context ARN (documentation account id)
tr 'context=dev-cluster ns=prod-db \[PROD\]' 'kubectl -n prod-db delete pod x'
tr 'context=prod-cluster ns=shop \[PROD\]'      'helm --kube-context prod-cluster uninstall shop -n shop'
tr 'context=dev2-cluster\)'                       'kubectl --context dev2-cluster exec -it x -- sh'
K8S_PROD_RE='staging' tr 'context=staging-cluster \[PROD\]' 'kubectl --context staging-cluster delete pod x'
