# shellcheck shell=bash
# Guard test rows for bundle github. Sourced by bundles/core/guard/tests/run.sh after lib.sh
# (helpers: t EXPECTED 'cmd' | tc EXPECTED CWD 'cmd' | tr 'reason-re' 'cmd' | g EXPECTED 'cmd' in a real dir).

# ---- GitHub (gh) -------------------------------------------------------------------
# lookups cd into the command's cwd, so gh write-gate rows run in an existing directory
# reads / passthrough
t pass  'gh pr view 100 --json title'
t pass  'gh pr list --state open'
t pass  'gh issue view 3 --comments'
t pass  'gh auth status'
t pass  'gh repo set-default o/r'
t pass  'gh config get git_protocol'
t pass  'gh api repos/o/r/pulls'
t pass  'gh api repos/o/r/pulls/1 --jq .title'
t pass  'gh api -X GET search/issues -f q=x'
t pass  'gh api --method GET repos/o/r/issues -F per_page=100'
t pass  "gh api graphql -f query='{ viewer { login } }'"
t pass  "gh api graphql -f query='query { repository(owner:\"o\", name:\"r\") { id } }'"
t pass  'gh api -X GET search/issues -f q=x && gh api repos/o/r'
t pass  'ls ~/.config/gh/'
# gh api writes ask
t ask   'gh api -X POST repos/o/r/issues -f title=x'
t ask   'gh api -XPOST repos/o/r/labels'
t ask   'gh api --method=patch repos/o/r'
t ask   'gh api -X DELETE repos/o/r/git/refs/heads/x'
t ask   'gh api repos/o/r/issues -f title=x'
t ask   'gh api repos/o/r/issues --input -'
t ask   'gh api repos/o/r && gh api repos/o/r/labels -f name=x'
t ask   "gh api graphql -f query='mutation { addStar(input:{starrableId:\"x\"}) { clientMutationId } }'"
t ask   'gh api graphql -F query=@q.graphql'
t ask   'gh api graphql -f query="$(cat q.graphql)"'
t ask   "gh api graphql -f query='query A { viewer { login } }' -f operationName=A"
t deny  'gh api repos/o/r/issues/3/comments -f body="Fixes #3"'
# token / credential denies
t deny  'gh auth token'
t deny  'GH_TOKEN=$(gh auth token) make release'
t deny  'gh auth status --show-token'
t deny  'gh auth status -h github.com -t'
t deny  'gh config get oauth_token -h github.com'
t deny  'cat ~/.config/gh/hosts.yml'
t deny  'grep oauth ~/.config/gh/hosts.yml'
tr 'gh auth status' 'cat ~/.config/gh/hosts.yml'
tr 'gh auth token prints' 'gh auth token'
# team-visible asks
t ask   'gh pr merge 100 --squash'
t ask   'gh -R o/r pr merge 100'
t ask   'gh pr review 100 --approve'
t ask   'gh pr update-branch 100'
t ask   'gh issue delete 1 --yes'
t ask   'gh issue transfer 1 o/other'
t ask   'gh issue develop 1 --checkout'
t ask   'gh repo fork o/r --remote'
t ask   'gh repo sync'
t ask   'gh repo edit --delete-branch-on-merge'
t ask   'gh label edit bug --color ff0000'
t ask   'gh workflow run ci.yml'
t ask   'gh run cancel 123'
t ask   'gh secret set TOKEN'
t ask   'gh gist create notes.md'
t ask   'gh auth switch'
t ask   'gh alias set co "pr checkout"'
t ask   'gh extension install owner/gh-x'
t ask   'gh release create v1.0.0'
tr 'human-only' 'gh pr merge 100'
# label create (positional name)
t allow 'gh label create agent-worked -c 7057ff -d "Worked by an AI agent"'
t allow 'gh label create -R o/r agent-drafted --force'
t ask   'gh label create bug'
t ask   'gh label create "$L"'
# pr create
t  allow 'gh pr create -H feat-x -B main -t "x" -b "body" -l agent-worked'
t  allow 'gh pr create -H feat-x-sub-01-schema -B feat-x -t x -l agent-worked'
t  allow 'gh pr create -R up/r -H me:feat-x-sub-01-schema -B feat-x -t x'
t  deny  'gh pr create --head=feat-x-sub-01-schema --base=master -t x'
t  deny  'gh pr create -H me:feat-x-sub-01-schema -B main -t x'
t  deny  'gh pr create -H feat-x-sub-01-schema -t x'
t  deny  'gh pr create -f -H feat-x-sub-01-schema -B main'            # -f is --fill (boolean)
t  ask   'gh pr create -H feat-x-sub-01-schema -B "$BR" -t x'
t  ask   'gh pr create -H "$BR" -B main -t x'
tc deny  '/home/u/dev/shop_feat-x-sub-01-schema' 'gh pr create -B feat-x -t x'
tc allow '/home/u/dev/shop_feat-x-sub-01-schema' 'gh pr create -H feat-x-sub-01-schema -B feat-x -t x'
GIT_STUB_BRANCH=feat-x-sub-01-schema t deny  'gh pr create -B main -t x'
GIT_STUB_BRANCH=feat-x-sub-01-schema t allow 'gh pr create -B feat-x -t x'
GIT_STUB_BRANCH=feat-x               t allow 'gh pr create -B main -t x'
t  deny  'gh pr create -H feat-x -B main -t a && gh pr create -H feat-x-sub-01-schema -B main -t b'
t  pass  'gh pr create --web -H feat-x-sub-01-schema'
t  pass  'gh pr create --dry-run -H feat-x-sub-01-schema -B main'
t  deny  'gh pr create -H feat-x -B main -t x -b "Fixes #3"'
t  allow 'gh pr create -H feat-x -B main -t x -b "part of #3, see #4"'
t  allow $'gh pr create -H feat-x -B main -t x -F - <<\'EOF\'\nit\'s done\nEOF'
tr 'target the ticket branch' 'gh pr create -H a-sub-01-x -B main'
# pr write gate
g allow 'gh pr edit 100 -b "new"'
g ask   'gh pr edit 200 -b new'
g allow 'gh pr edit 200 --add-label agent-worked'
g allow 'gh pr edit 200 -R o/r --add-label agent-worked'
g ask   'gh pr edit 200 --add-label agent-worked --title x'
g allow 'gh pr comment "#100" -b hi'
g allow 'gh pr comment feat-x -b hi'
g allow 'gh pr comment https://github.com/o/r/pull/100 -b hi'
g allow 'gh pr comment 100 --edit-last -b hi'
g ask   'gh pr comment -b hi'
g ask   'gh pr comment #100 -b hi'                  # unquoted # is a shell comment → no ref
g ask   'gh pr comment "$N" -b hi'
g ask   'gh pr comment 300 -b hi'
t ask   'gh pr comment 100 -b hi'                   # cwd does not exist → lookup fails → ask
g allow 'gh pr ready --undo 110'
g allow 'gh -R o/r pr comment 100 -b hi'
g allow 'gh pr -R o/r close 100 -d'
g ask   'gh pr close 200'
g ask   'gh pr reopen 200'
g ask   'gh pr comment 120 -b hi'                   # cross-repository (fork) PR
g deny  'gh pr edit 110 -B main'
g deny  'gh pr edit 210 --base main'
g allow 'gh pr edit 110 --base feat-x'
g ask   'gh pr edit 210 -B feat-x'
g allow 'gh pr edit 100 -B main'
g ask   'gh pr comment 100 -b x && gh pr comment 200 -b y'
g deny  'gh pr comment 200 -b x && gh pr edit 110 -B main'
g deny  'gh pr merge 100 -b "Closes #3"'
g deny  'gh pr edit 100 -b "Resolves o/r#3"'
g ask   'GH_REPO=o/r gh pr comment 100 -b hi'
# issue create: provenance label required
t allow 'gh issue create -t x -b y -l agent-drafted'
t allow 'gh issue create -R o/r -t x -l bug,agent-drafted'
t allow 'gh issue create -t x -l bug -l agent-created'
t allow 'gh issue create --label=agent-drafted -t x'
t deny  'gh issue create -t x -l bug'
t deny  'gh issue create -t x'
t deny  'gh issue create -t agent-drafted -l bug'
t deny  'gh issue create -t a -l agent-drafted && gh issue create -t b'
t pass  'gh issue create --web'
tr 'provenance label' 'gh issue create -t x'
# issue write gate
g allow 'gh issue edit 1 2 --add-label bug'
g ask   'gh issue edit 1 3 --add-label bug'
g allow 'gh issue edit 3 --add-label agent-worked'
g allow 'gh issue edit 3 4 --add-label agent-worked,agent-drafted'
g allow 'gh issue edit 1 --add-sub-issue 5'
g allow 'gh issue edit -R o/r 1 --add-label x'
g allow 'gh issue comment 1 -b hi'
g allow 'gh issue comment 2 -b hi'
g allow 'gh issue comment "#1" -b hi'
g allow 'gh issue comment https://github.com/o/r/issues/1 -b hi'
g ask   'gh issue comment 3 -b hi'
g ask   'gh issue comment 4 -b hi'
g ask   'gh issue comment 9 -b hi'
g allow 'gh issue close 1 -c "done" -r completed'
g deny  'gh issue close 3'
g deny  'gh issue reopen 3'
g deny  'gh issue comment 3 -b x && gh issue close 3'
g ask   'gh issue close 9'
g ask   'gh issue close "$N"'
WORK_TICKET_ALLOW_TRANSITION=1 g ask 'gh issue close 3'
g ask   'gh issue comment 3 -b "fixes #3 landed"'
g allow 'gh issue comment 1 -b "fixes #3 landed"'
# GitHub closing keywords in commits
t deny  'git commit -m "Fixes #12"'
t deny  'git commit -m "Resolves: o/r#7"'
t deny  'git commit -m "closed https://github.com/o/r/issues/7"'
t pass  'git commit -m "see #12"'
t pass  'git commit -m "implements #12"'
t pass  'git commit -m "prefix #12 cleanup"'
tr 'GitHub close the issue' 'git commit -m "Fixes #12"'
